#:schema node_modules/wrangler/config-schema.json
name = "beatswipe"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"

[build]
command = """
mkdir -p dist
cp -r public/* dist/
ls -la dist/
"""

[durable_objects]
bindings = [
  { name = "GAME_SESSIONS", class_name = "GameSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameSession"]

[ai]
binding = "AI"

[observability.logs]
enabled = true